### PR TITLE
Remove optional dependency for API version via setter

### PR DESCRIPTION
**Pull request by legionth**

### CODE REVIEW

**Comment by legionth** [comment]
Resolve Merge conflicts. Ready for review 👍

**Comment by dkaisers** [comment]
@legionth Because of the merge of #30 this conflicted again.

**Comment by legionth** [comment]
Merge Conflicts resolved :shipit:

**Comment by jayay** [comment]
I'm not a huge fan of this. An instance of `onOfficeSDK` cannot be created at any time anymore with this change. I'd prefer to have as many classes as possible stateless in order to use dependency injection safely.

**Comment by legionth** [comment]
A dependency should never be optional. A dependency is a dependency there is no "optional", the object should depend on it or not, nothing between. And therfore the only injection point to define suche a dependency is the **constructor**. The constructor decides **what is needed** to create the object, nobody else should be able to change that.

A method should always be considered as a **transaction** like:  `sendRequest($request)`, `animate()`, `save($something)`. That is why [Getters and Setters](https://www.javaworld.com/article/2073723/why-getter-and-setter-methods-are-evil.html) should be considered as evil. They lead to create incomplete objects, which leads to additonal documentation, which wouldn't be needed in the first place.

I would prefer that this library is developed extremly defensive. A software/library that can not be misused in any form, by forgetting a dependency etc., because we prevent that it the very first place.
For instance: Currently we are violating the [Law of Demeter](https://en.wikipedia.org/wiki/Law_of_Demeter), because we are using `setters` in the `onOfficeSDK` class, to set parameters in `ApiCall`.

> An instance of onOfficeSDK cannot be created at any time anymore with this change.

I don't understand this statement? Do you mean that this is different to the current behavior? If you could explain it, I may be able to follow your words 👍 

>  I'd prefer to have as many classes as possible stateless in order to use dependency injection safely.

Me too, but currently, a created object can switch its state during runtime, because these setters allow it.

**Comment by jayay** [comment]
My whole point is, it'd be nicer to move all the request-related data into a class dedicated to request data.
It would contain things such as API branch, token, HMAC, Action ID, Parameters and whatnot. The onOfficeSDK could be constructed at any time and could be reused, for example if used to make calls for different customers.

**Comment by legionth** [comment]
> My whole point is, it'd be nicer to move all the request-related data into a class dedicated to request data.
It would contain things such as API branch, token, HMAC, Action ID, Parameters and whatnot. The onOfficeSDK could be constructed at any time and could be reused, for example if used to make calls for different customers.

That is something we all want. But IMO we must take baby steps first, to get to an API we all can agree on. We could create a big change set and overhaul the API entirely, but would recommend to take small steps, so everyone using this API can understand the history of changes. There is always the risk during big changes that we haven't considered yet. That's why I would recommend to make many small changes over one  big change.

This PR is just the beginning, before we moving step by step to an API client, that we think is the best user experience.

**Comment by jayay** [comment]
I'd like to ask @dkaisers about this.

**Comment by dkaisers** [comment]
I'm all for immutable objects where everything is set in the constructor and fixed after that. That being said, in my opinion, classes should be split between ones with state and ones with logic. That means having data model classes which only contain stateful datatypes (string, int, etc. but also other data models) and having classes which have either no dependencies or just other logic classes.

In this case, I'm for @jayay's proposal of moving the api version to the specific request. I also understand, why it is important to make many small changes. But I'm not sure, if this change is necessary.

Maybe, we lack a common plan and vision for the future of this library at the moment. So, defining the future interfaces and ways this SDK should work around first, before making these kinds of changes, may be the better way to go. Otherwise, this kind of discussion will just repeat itself with a lot of changes.

Having a plan is always good. And being able derive the necessary (small) steps to take from it, for this library to get better, is probably smarter than just changing stuff around until it fits.

**Comment by legionth** [comment]
I will close this PR. I think we will take a different approach here.

**Pull request closed without merging**
