### PR TITLE
Introduce PSR-4 Autoloader via Composer

### PR DESCRIPTION
**Pull request by legionth**
[PSR-4](https://www.php-fig.org/psr/psr-4/) is the current standard in PHP Open Source Projects.

This project has currently a PSR4-Autoloader itself, but it would need extra steps to set this project for the environment.

Using the composer autoloader makes this a lot easier to use in external projects. Just hit composer install, and let's go.
Additional creating a general test environment(for PHPUnit) will be a lot easier.

### CODE REVIEW

**Comment by jayay** [comment]
Please keep in mind this will have to introduce a major version bump.

**Comment by legionth** [comment]
> Please keep in mind this will have to introduce a major version bump.

I think we will have a bit more features, before we release the next version ;) But you are absolutely right, we need to create a major version after this.

Maybe we should create Roadmap to keep everybody on track for the first major release?

**Comment by jayay** [comment]
> Maybe we should create Roadmap to keep everybody on track for the first major release?

Sounds great!

**Comment by legionth** [comment]
See #8

**Pull request merged**
