### PR TITLE
now initializing the timestamp parameter in case it is not set manually

### PR DESCRIPTION
**Pull request by AndrejThomsen**
fixes #2914681, where the timestamp may become null

### CODE REVIEW

**Review by legionth — CHANGES_REQUESTED** [review]
In general LGTM.
Could you check: https://github.com/AndrejThomsen/sdk/blob/49889d04a74bb1380d42cd59d9bd1f517af9a6c7/tests/RequestTest.php#L43

And adapt the test so it is ensured that this problem can't get in so easily again?

**Review by legionth — APPROVED** [review]
LGTM 👍

**Comment by jayay** [comment]
@legionth this modifies the public interface of `ApiAction`. Do you think that can become a problem?

**Comment by legionth** [comment]
I can't see where this PR touches the `ApiAction`. Could you point out the part, where this could be a problem?

As far as I can see this PR handles only internal methods and this shouldn't be a problem for end-users of this library.

**Comment by jayay** [comment]
You're right, it was the previous PR that modified the constructor of `ApiAction`.

**Pull request merged**
